### ISSUE TITLE
Gulp fails when trying to build page on client side example

### ISSUE THREAD

**Issue by AlexandroDRK** [B3rn475/IFMLEdit.org#37]
```
'js' errored after 2.43 s
[21:52:11] Error: Parse Error: <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=""#landmark-menu">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="landmark-menu" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
        </ul>
    </div>
</nav>
<div class="container">
    <span data-bind="if: active() === 'mails'">
        <c-mails params="context: context" class="container"></c-mails>
    </span>
</div>
 (while stringify was processing /home/alexandro/Downloads/clientexample/src/js/controls/main-application/index.html) while parsing file: /home/alexandro/Downloads/clientexample/src/js/controls/main-application/index.html
    at new HTMLParser (/home/alexandro/Downloads/clientexample/node_modules/html-minifier/src/htmlparser.js:235:13)
    at minify (/home/alexandro/Downloads/clientexample/node_modules/html-minifier/src/htmlminifier.js:946:3)
    at exports.minify (/home/alexandro/Downloads/clientexample/node_modules/html-minifier/src/htmlminifier.js:1299:10)
    at minify (/home/alexandro/Downloads/clientexample/node_modules/stringify/src/stringify.js:147:27)
    at Stream.transformFn (/home/alexandro/Downloads/clientexample/node_modules/stringify/src/stringify.js:209:24)
    at Stream.end (/home/alexandro/Downloads/clientexample/node_modules/browserify-transform-tools/lib/transformTools.js:108:30)
    at _end (/home/alexandro/Downloads/clientexample/node_modules/through/index.js:65:9)
    at stream.end (/home/alexandro/Downloads/clientexample/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/alexandro/Downloads/clientexample/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)
[21:52:11] 'build' errored after 2.45 s
[21:52:11] 'default' errored after 2.62 s
```

**Comment by AlexandroDRK** [comment]
@B3rn475 I need you help again on this issue

**Comment by B3rn475** [comment]
It should be fixed now.

Feel free to reopen if it is not.
